on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Get Cache dependencies
        uses: actions/cache@v4
        id: files-cache
        with:
          path: |
            node_modules
            /tmp/.__tmp_int
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install NPM Dependencies
        if: steps.files-cache.outputs.cache-hit != 'true'
        run: npm ci

  unit-tests:
    needs: build
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Get Cache dependencies
        uses: actions/cache@v4
        id: files-cache
        with:
          path: |
            node_modules
            /tmp/.__tmp_int
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Run test script
        run: npm run test

  integration-tests:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Get Cache dependencies
        uses: actions/cache@v4
        id: files-cache
        with:
          path: |
            node_modules
            /tmp/.__tmp_int
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm run prepare-integration-tests
      - name: Run test-integration script (using Xvfb)
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test-integration
